routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'DashboardController@index')->name('simulation')->middleware('auth');
Route::get('/simulator', 'SimulationController@index')->name('simulator')->middleware('user');

Route::get('/performance_analysis/{game_play_id}', 'ReportsController@performanceAnalysis')->name('performance_analysis')->middleware('user'); 
Route::get('/comparative_analysis', 'ReportsController@comparativeAnalysis')->name('comparative_analysis')->middleware('user');
Route::get('/personal_shifts', 'ReportsController@personalShifts')->name('personal_shifts')->middleware('user');
Route::get('/leaderboard', 'ReportsController@leaderboard')->name('leaderboard')->middleware('user');

Route::resource('user', 'UserController')->middleware('super_admin');
Route::get('user/edit/{id}', 'UserController@edit')->name('user.edit')->middleware('auth');
Route::put('user/edit/{id}', 'UserController@update')->name('user.save')->middleware('auth');
Route::resource('session', 'SessionController')->middleware('super_admin');
Route::resource('profile', 'ProfileController')->middleware('auth');

Route::prefix('ajax')->middleware('user')->name('ajax.')->group(function(){
	Route::get('getObservations', 'AjaxController@observation')->name('observation');
	Route::post('startGame', 'AjaxController@startGame')->name('start_game');
	Route::post('endGame', 'AjaxController@endGame')->name('end_game');
	Route::post('nextStage', 'AjaxController@nextStage')->name('next_stage');
	Route::post('observed', 'AjaxController@observed')->name('observed');
	Route::post('engagedAfterObserving', 'AjaxController@engagedAfterObserving')->name('engaged_after_observing');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function session()
    {
        return $this->belongsTo(Sessions::class, 'session_id');
    }

    public function gamePlays()
    {
        return $this->hasMany(GamePlay::class);
    }

    /**
     * Scope a query to only include particular session users.
     *
     * @param \Illuminate\Database\Eloquent\Builder $query
     * @return \Illuminate\Database\Eloquent\Builder
     */
    public function scopeSession($query, $session_id = '')
    {
        return empty($session_id) ? $query : $query->where('session_id', $session_id);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\Project;
use App\Sessions;
use App\PersonalityType;
use Validator;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.index', ['users' => User::where('user_type', 'user')->session(request('session_id'))->get(), 'sessions' => Sessions::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create', [/*'projects' => Project::all(),*/ 'sessions' => Sessions::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            // 'project_id.required' => 'Project is Required',
            // 'project_id.exist'    => 'Project Doesn\'t Exist',
            'session_id.required' => 'Session is Required',
            'session_id.exist'    => 'Session Doesn\'t Exist',
            'name.required'       => 'Name is Required',
            'name.max'            => 'Name is too long',
            'email.required'      => 'Email is Required',
            'email.email'         => 'Email Format is Invalid',
            'email.unique'        => 'Email Already Exists',
            'password.required'   => 'Password is Required',
            'password.min'        => 'Password Cannot be Shorter Than 6',
            'password.confirmed'  => 'Password & Confirm Password Doesn\'t Match'
          ];
        Validator::make($request->all(), [
            // 'project_id'              => 'required|exists:projects,id',
            'session_id'              => 'required|exists:sessions,id',
            'name'                    => 'required|max:255',
            'email'                   => 'required|email|unique:users,email',
            'password'                => 'required|min:6|confirmed',
        ], $messages)->validate();

        $user               = new User;
        $user->name         = $request->name;
        $user->email        = $request->email;
        $user->password     = bcrypt($request->password);
        $user->session_id   = $request->session_id;
        $user->user_type    = "user";
        $user->save();

        return redirect()->route('user.index')->with(['response' => ['status' => "success", 'message' => "User created successfully."]]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('user.show', ['user' => User::findOrFail($id)]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(!\Auth::id() != $id && !\Auth::user()->user_type == 'super_admin')
            abort(403);

        return view('user.edit', ['user' => User::findOrFail($id), 'sessions' => Sessions::all(), 'personalityTypes' => PersonalityType::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(!\Auth::id() != $id && !\Auth::user()->user_type == 'super_admin')
            abort(403);

        $user = User::findOrFail($id);

        $messages = [
            'nick_name.required'       => 'Nickname is Required',
            'nick_name.max'            => 'Nickname is too long',
            'personality_type_id.exists' => 'Personality Type Doesn\'t Exists',
            'gender'                  => 'Invalid Gender',
          ];
        Validator::make($request->all(), [
            'nick_name'                    => 'required|max:255',
            'personality_type_id'         => 'sometimes|exists:personality_types,id',
            'gender'                      => 'sometimes|in:male,female,undefined',
        ], $messages)->validate();
        
        $user->nick_name            = $request->nick_name;
        $user->personality_type_id  = $request->personality_type_id;
        $user->gender               = $request->gender;
        $user->education_level      = $request->education_level;
        $user->organization_type    = $request->organization_type;
        $user->organization_size    = $request->organization_size;
        $user->industry             = json_encode($request->industry);
        $user->function             = json_encode($request->function);
        $user->career_level         = $request->career_level;
        $user->working_experience   = $request->working_experience;
        $user->save();

        return redirect()->route(\Auth::user()->user_type == 'super_admin' ? 'user.index' : 'simulation')->with(['response' => ['status' => "success", 'message' => "User created successfully."]]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('user.index')->with(['response' => ['status' => "success", 'message' => "User removed successfully."]]);
    }
}

resources/views/user/create.blade.php
@extends('adminlte::page')

@section('title', 'New User - SIMMETRIC:GAIA')

@section('content_header')
<h1>New User</h1>
<br>
@endsection

@section('content')
<div class="row">
      <div class="col-md-12">
        <div class="col-md-offset-3 col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add User Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           <form action="{{ route('user.store') }}" method="post">
             @csrf
              <div class="box-body">
                {{-- <div class="form-group {{ $errors->has('project_id') ? 'has-error' : ''}}">
                  <label for="name">Project</label>
                  <select class="form-control" id="project_id" name="project_id">
                    <option value="">Select Project</option>
                    @foreach ($projects as $project)
                     <option value="{{$project->id}}" {{ $project->id == old('project_id') ? 'selected' : ''}}>{{$project->title }}</option>
                    @endforeach
                  </select>
                  @if ($errors->has('project_id'))
                    <span class="help-block text-danger">{{ $errors->first('project_id') }}</span>
                  @endif
                </div> --}}
                <div class="form-group {{ $errors->has('session_id') ? 'has-error' : ''}}">
                  <label for="name">Session</label>
                  <select class="form-control" id="session_id" name="session_id">
                    <option value="">Select a Session</option>
                    @foreach ($sessions as $session)
                     <option value="{{$session->id}}" {{ $session->id == old('session_id') ? 'selected' : ''}}>{{$session->title }}</option>
                    @endforeach
                  </select>
                  @if ($errors->has('session_id'))
                    <span class="help-block text-danger">{{ $errors->first('session_id') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('name') ? 'has-error' : ''}}">
                  <label for="phone">Name</label>
                  <input type="text" class="form-control" name="name" id="name" placeholder="Enter Name" value="{{ old('name') }}">
                  @if ($errors->has('name'))
                    <span class="help-block text-danger">{{ $errors->first('name') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('email') ? 'has-error' : ''}}">
                  <label for="phone">Email</label>
                  <input type="email" class="form-control" name="email" id="email" placeholder="Enter Email Address" value="{{ old('email') }}">
                  @if ($errors->has('email'))
                    <span class="help-block text-danger">{{ $errors->first('email') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('password') ? 'has-error' : ''}}">
                  <label for="phone">Password</label>
                  <input type="password" class="form-control" name="password" id="password" placeholder="Enter Password" value="">
                  @if ($errors->has('password'))
                    <span class="help-block text-danger">{{ $errors->first('password') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('password_confirmation') ? 'has-error' : ''}}">
                  <label for="phone">Confirm Password</label>
                  <input type="password" class="form-control" name="password_confirmation" id="password_confirmation" placeholder="Enter Confirm Password" value="">
                  @if ($errors->has('password_confirmation'))
                    <span class="help-block text-danger">{{ $errors->first('password_confirmation') }}</span>
                  @endif
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
        </div>
      </div>
@endsection

@push('js')

@endpush

resources/views/user/index.blade.php
@extends('adminlte::page')

@section('title', 'SIMMETRIC:GAIA')

@section('content')
	<div class="content-wrapper">
		<section class="content-header">
			<h1 class="pull-left">Users</h1>
			<a href="{{ route('user.create') }}">
				<button class="btn btn-primary pull-right">Add New</button>
			</a>
			<div class="clearfix"></div>
		</section>
		<br>
		<section class="content">
			<div class="box">
	            <div class="box-body">
	            	<form class="form-inline" action="{{ route('user.index') }}" method="GET">
	            		<div class="form-group">
      						<label for="email">Sessions:</label>
	            			<select class="form-control" name="session_id">
	            				<option value="">All Sessions</option>
	            				@foreach($sessions as $session)
	            					<option value="{{ $session->id }}" {{ $session->id == request('session_id') ? 'selected' : '' }}>{{ $session->title }}</option>
	            				@endforeach
	            			</select>
	            		</div>
	            		<button type="submit" class="btn btn-primary">Go</button>
	            	</form>
	            	<table class="table table-bordered table-striped" id="table">
	            		<thead>
	            			<tr>
	            				<th>Sr#</th>
	            				<th>Name</th>
	            				<th>Email Address</th>
	            				<th>Project</th>
	            				<th>Session</th>
	            				<th>Total Attempts</th>
	            				<th>Action</th>
	            			</tr>
	            		</thead>
	            		<tbody>
	            			@foreach($users as $user)
		            			<tr>
		            				<td>{{ $loop->iteration }}</td>
		            				<td>{{ $user->name }}</td>
		            				<td>{{ $user->email }}</td>
		            				<td>{{ $user->session->project->title }}</td>
		            				<td>{{ $user->session->title }}</td>
		            				<td>{{ $user->gamePlays->count() }}</td>
		            				<td>
		            					{{-- <a href="{{ route('user.show', $user->id) }}" class="btn btn-xs btn-success" title="View"><i class="fa fa-eye"></i></a> --}}
		            					{{-- <a href="{{ route('user.edit', $user->id) }}" class="btn btn-xs btn-warning" title="Edit"><i class="fa fa-edit"></i></a> --}}
		            					<form action="{{ route('user.destroy', $user->id) }}" method="POST" style="display: inline;">
										    <input type="hidden" name="_method" value="DELETE">
										    <input type="hidden" name="_token" value="{{ csrf_token() }}">
										    <button type="submit" class="btn btn-xs btn-danger remove" title="Remove"><i class="fa fa-remove"></i></button>
										</form>
		            					{{-- <a href="" class="btn btn-xs btn-danger remove" title="Remove"><i class="fa fa-remove"></i></a> --}}
		            				</td>
		            			</tr>
	            			@endforeach
	            		</tbody>
	            	</table>
	            </div>
	        </div>
		</section>
	</div>
@endsection

@push('js')
<script type="text/javascript">
	$('#table').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    })
</script>
@endpush

resources/views/user/show.blade.php
@extends('adminlte::page')

@section('title', 'SIMMETRIC:GAIA')

@section('content')
	<div class="content-wrapper">
		<section class="content-header">
			<h1>Users</h1>
		</section>
		<section class="content">
			<div class="box">
	            <div class="box-body">
	            	<table class="table table-bordered table-hover">
	            		<tr>
	            			<td class="boldIt">Name</td>
	            			<td>{{ $user->name }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Email</td>
	            			<td>{{ $user->email }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Gender</td>
	            			<td>{{ $user->gender }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Education Level</td>
	            			<td>{{ $user->education_level }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Organization Type</td>
	            			<td>{{ $user->organization_type }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Organization Size</td>
	            			<td>{{ $user->organization_size }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Industry</td>
	            			<td>{{ $user->industry }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Function</td>
	            			<td>{{ $user->function }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Career Level</td>
	            			<td>{{ $user->career_level }}</td>
	            		</tr>
	            		<tr>
	            			<td class="boldIt">Working Experience</td>
	            			<td>{{ $user->working_experience }}</td>
	            		</tr>
	            		<tr>
	            			<td colspan="2"></td>
	            		</tr>
	            	</table>
	            </div>
	        </div>
	    </section>
@endsection
@push('css')
	<style type="text/css">
		.boldIt{
			font-weight: bold;
		}
	</style>
@endpush