routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'DashboardController@index')->name('simulation')->middleware('auth');
Route::get('/simulator', 'SimulationController@index')->name('simulator')->middleware('user');

Route::get('/performance_analysis/{game_play_id}', 'ReportsController@performanceAnalysis')->name('performance_analysis')->middleware('user'); 
Route::get('/comparative_analysis', 'ReportsController@comparativeAnalysis')->name('comparative_analysis')->middleware('user');
Route::get('/personal_shifts', 'ReportsController@personalShifts')->name('personal_shifts')->middleware('user');
Route::get('/leaderboard', 'ReportsController@leaderboard')->name('leaderboard')->middleware('user');

Route::resource('user', 'UserController')->middleware('super_admin');
Route::get('user/edit/{id}', 'UserController@edit')->name('user.edit')->middleware('auth');
Route::put('user/edit/{id}', 'UserController@update')->name('user.save')->middleware('auth');
Route::resource('session', 'SessionController')->middleware('super_admin');
Route::resource('profile', 'ProfileController')->middleware('auth');

Route::prefix('ajax')->middleware('user')->name('ajax.')->group(function(){
	Route::get('getObservations', 'AjaxController@observation')->name('observation');
	Route::post('startGame', 'AjaxController@startGame')->name('start_game');
	Route::post('endGame', 'AjaxController@endGame')->name('end_game');
	Route::post('nextStage', 'AjaxController@nextStage')->name('next_stage');
	Route::post('observed', 'AjaxController@observed')->name('observed');
	Route::post('engagedAfterObserving', 'AjaxController@engagedAfterObserving')->name('engaged_after_observing');
});

app/Sessions.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Sessions extends Model
{
    public function project()
    {
    	return $this->belongsTo(Project::class);
    }

    public function users()
    {
    	return $this->hasMany(User::class, 'session_id');
    }
}

app/Http/Controllers/SessionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Sessions;
use App\Project;
use Validator;

class SessionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('session.index')->with(['sessions' => Sessions::all()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('session.create')->with(['projects' => Project::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $messages = [
            'project_id.required' => 'Project is Required',
            'project_id.exist'    => 'Project Doesn\'t Exist',
            'title.required'      => 'Session Title is Required',
          ];
        Validator::make($request->all(), [
            'project_id'              => 'required|exists:projects,id',
            'title'                   => 'required|max:255',
        ], $messages)->validate();

        $session = new Sessions;
        $session->project_id = $request->project_id;
        $session->title      = $request->title;
        $session->save();

        return redirect()->route('session.index')->with(['response' => ['status' => "success", 'message' => "Session created successfully."]]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $session = Sessions::findOrFail($id);

        return view('session.edit')->with(['session' => $session, 'projects' => Project::all()]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $session = Sessions::findOrFail($id);

        $messages = [
            'project_id.required' => 'Project is Required',
            'project_id.exist'    => 'Project Doesn\'t Exist',
            'title.required'      => 'Session Title is Required',
          ];
        Validator::make($request->all(), [
            'project_id'              => 'required|exists:projects,id',
            'title'                   => 'required|max:255',
        ], $messages)->validate();

        $session->project_id = $request->project_id;
        $session->title      = $request->title;
        $session->save();

        return redirect()->route('session.index')->with(['response' => ['status' => "success", 'message' => "Session updated successfully."]]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $session = Sessions::findOrFail($id);
        $session->delete();

        return redirect()->route('session.index')->with(['response' => ['status' => "success", 'message' => "Session removed successfully."]]);
    }
}

resources/views/session/create.blade.php
@extends('adminlte::page')

@section('title', 'New Session - SIMMETRIC:GAIA')

@section('content_header')
<h1>New Session</h1>
<br>
@endsection

@section('content')
<div class="row">
      <div class="col-md-12">
        <div class="col-md-offset-3 col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Add Session Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           <form action="{{ route('session.store') }}" method="post">
             @csrf
              <div class="box-body">
                <div class="form-group {{ $errors->has('project_id') ? 'has-error' : ''}}">
                  <label for="name">Project</label>
                  <select class="form-control" id="project_id" name="project_id">
                    <option value="">Select Project</option>
                    @foreach ($projects as $project)
                     <option value="{{$project->id}}" {{ $project->id == old('project_id') ? 'selected' : ''}}>{{$project->title }}</option>
                    @endforeach
                  </select>
                  @if ($errors->has('project_id'))
                    <span class="help-block text-danger">{{ $errors->first('project_id') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
                  <label for="phone">Session Title</label>
                  <input type="text" class="form-control" name="title" id="title" placeholder="Enter Session Title" value="{{ old('title') }}">
                  @if ($errors->has('title'))
                    <span class="help-block text-danger">{{ $errors->first('title') }}</span>
                  @endif
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
        </div>
      </div>
@endsection

@push('js')

@endpush

resources/views/session/edit.blade.php
@extends('adminlte::page')

@section('title', 'New Session - SIMMETRIC:GAIA')

@section('content_header')
<h1>Edit Session</h1>
<br>
@endsection

@section('content')
<div class="row">
      <div class="col-md-12">
        <div class="col-md-offset-3 col-md-6">
          <!-- general form elements -->
          <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">Update Session Details</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
           <form action="{{ route('session.update', $session->id) }}" method="post">
             @csrf
             @method('PUT')
              <div class="box-body">
                <div class="form-group {{ $errors->has('project_id') ? 'has-error' : ''}}">
                  <label for="name">Project</label>
                  <select class="form-control" id="project_id" name="project_id">
                    <option value="">Select Project</option>
                    @foreach ($projects as $project)
                     <option value="{{$project->id}}" {{ $project->id == old('project_id', $session->project_id) ? 'selected' : ''}}>{{$project->title }}</option>
                    @endforeach
                  </select>
                  @if ($errors->has('project_id'))
                    <span class="help-block text-danger">{{ $errors->first('project_id') }}</span>
                  @endif
                </div>
                <div class="form-group {{ $errors->has('title') ? 'has-error' : ''}}">
                  <label for="phone">Session Title</label>
                  <input type="text" class="form-control" name="title" id="title" placeholder="Enter Session Title" value="{{ old('title', $session->title) }}">
                  @if ($errors->has('title'))
                    <span class="help-block text-danger">{{ $errors->first('title') }}</span>
                  @endif
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </form>
          </div>
          <!-- /.box -->
        </div>
        </div>
      </div>
@endsection

@push('js')

@endpush

resources/views/session/index.blade.php
@extends('adminlte::page')

@section('title', 'Sessions - SIMMETRIC:GAIA')

@section('content')
	<div class="content-wrapper">
		<section class="content-header">
			<h1 class="pull-left">Sessions</h1>
			<a href="{{ route('session.create') }}">
				<button class="btn btn-primary pull-right">Add New</button>
			</a>
			<div class="clearfix"></div>
		</section>
		<br>
		<section class="content">
			<div class="box">
	            <div class="box-body">
	            	<table class="table table-bordered table-striped" id="table">
	            		<thead>
	            			<tr>
	            				<th>Sr#</th>
	            				<th>Date</th>
	            				<th>Project</th>
	            				<th>Title</th>
	            				<th>Total Users</th>
	            				<th>Action</th>
	            			</tr>
	            		</thead>
	            		<tbody>
	            			@foreach($sessions as $session)
	            				<tr>
	            					<td>{{ $loop->iteration }}</td>
	            					<td>{{ $session->created_at->format('d/m/Y') }}</td>
	            					<td>{{ $session->project->title }}</td>
	            					<td>{{ $session->title }}</td>
	            					<td>{{ $session->users->count() }}</td>
	            					<td>
	            						{{-- <a href="{{ route('session.show', $session->id) }}" class="btn btn-xs btn-success" title="View"><i class="fa fa-eye"></i></a> --}}
		            					{{-- <a href="{{ route('session.edit', $session->id) }}" class="btn btn-xs btn-warning" title="Edit"><i class="fa fa-edit"></i></a> --}}
		            					<form action="{{ route('session.destroy', $session->id) }}" method="POST" style="display: inline;">
										    <input type="hidden" name="_method" value="DELETE">
										    <input type="hidden" name="_token" value="{{ csrf_token() }}">
										    <button type="submit" class="btn btn-xs btn-danger remove" title="Remove"><i class="fa fa-remove"></i></button>
										</form>
	            					</td>
	            				</tr>
	            			@endforeach
	            		</tbody>
	        		</table>
	        	</div>
	        </div>
        </section>
    </div>
@endsection

@push('js')
<script type="text/javascript">
	$('#table').DataTable({
      'paging'      : true,
      'lengthChange': false,
      'searching'   : true,
      'ordering'    : true,
      'info'        : true,
      'autoWidth'   : false
    });
</script>
@endpush

resources/views/session/show.blade.php
@extends('adminlte::page')

@section('title', 'Session Details - SIMMETRIC:GAIA')

@section('content')
<div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <a href="{{ route('session.create') }}"><button class="btn btn-primary add-btn-right">Add New</button></a>
            </div>
            <div class="box-body table-responsive no-padding">
              <table class="table table-bordered">
                <tr>
                  <th>Port Name</th>
                  <td>{{ $port_detial->name }}</td>
                </tr>
                <tr>
                  <th>Phone</th>
                  <td>{{ $port_detial->phone }}</td>
                </tr>
                <tr>
                  <th>Email</th>
                  <td>{{ $port_detial->primary_email }}</td>
                </tr>
                 <tr>
                  <th>Address</th>
                  <td>{{ $port_detial->address }}</td>
                </tr>
                <tr>
                  <th>Postal Code</th>
                  <td>{{ $port_detial->postal_code }}</td>
                </tr>
                 <tr>
                  <th>Country</th>
                  <td>{{ $port_detial->country->name }}</td>
                </tr>
                 <tr>
                  <th>State</th>
                  <td>{{ $port_detial->state->name }}</td>
                </tr>
                 <tr>
                  <th>City</th>
                  <td>{{ $port_detial->city->name }}</td>
                </tr>
              </table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
@endsection